name: docker-tests-node-client

services:

  marklogic:
    image: "${MARKLOGIC_IMAGE}"
    platform: linux/amd64
    # The NET_RAW capability allows a process to create raw sockets. Polaris does not like that.
    # This setting removes the NET_RAW capability from the container.
    cap_drop:
      - NET_RAW
    environment:
      - INSTALL_CONVERTERS=true
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
    volumes:
      - ${MARKLOGIC_LOGS_VOLUME}:/var/opt/MarkLogic/Logs
    ports:
      - 8000-8017:8000-8017
      - 8024-8029:8024-8029
      - 8079:8079
