name: node-client

services:

  marklogic:
    image: "progressofficial/marklogic-db:latest"
    # image: "ml-docker-db-dev-tierpoint.bed-artifactory.bedford.progress.com/marklogic/marklogic-server-ubi:latest-12"
    platform: linux/amd64
    environment:
      - INSTALL_CONVERTERS=true
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/marklogic/logs:/var/opt/MarkLogic/Logs
    ports:
      - 8000-8002:8000-8002
      - 8015-8016:8015-8016
